version: "3.3"
services:
  workspace:
    build: ./docker/alpine
    ports:
      - "9000:9000"
    volumes:
      - ${DATA_SRC:-../src}:/var/www/html

  nginx:
    image: nginx:alpine
    depends_on:
      - workspace
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:delegated
      - ${DATA_SRC:-../src}:/var/www/html

  mariadb:
    image: mariadb:10.6.1
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
      MARIADB_USER: ${DB_USER:-default}
      MARIADB_PASSWORD: ${DB_PASS:-secret}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ${DB_DATA:-./datadir}:/var/lib/mysql:delegated
      - ./docker/mariadb:/docker-entrypoint-initdb.d:delegated

  adminer:
    image: adminer:4.8.0
    depends_on:
      - mariadb
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - "8080:8080"

  wpcli:
    image: wordpress:cli-php7.4
    depends_on:
      - mariadb
      - workspace
    user: "1000"
    entrypoint: wp  
    command: "--info"
    volumes:
      - ${DATA_SRC:-../src}:/var/www/html